### ISSUE TITLE
Migrate Wings

### ISSUE THREAD

**Issue by sirspock** [mintproject/it-mgmt#2]
- [x] Install WINGS
- [ ] Configure WINGS to run with Pegasus (depends on #5)
- [ ] Migrate domains from WINGS deployment on workflow.isi.edu

**Comment by sirspock** [comment]
@rafaelfsilva Do you want to move the wings instance running in workflow.isi.edu?

**Comment by mayani** [comment]
@sirspock Moving WINGS out of workflow will require a little thought and coordination. We will need to setup Pegasus, HTCondor, Singularity on mint.isi.edu edu for the workflows to work.

**Comment by sirspock** [comment]
@rafaelfsilva is doing it.
The new urls are:
wings.mint.isi.edu
mint.isi.edu
