### ISSUE TITLE
Install Pegasus services on MINT server

### ISSUE THREAD

**Issue by rafaelfsilva** [mintproject/it-mgmt#5]
- [x] Install HTCondor
- [x] Install Pegasus
- [x] Install Singularity
- [x] Configure CVMFS
- [ ] Configure Pegasus to submit to OSG

**Comment by mayani** [comment]
We should only do "Configure Pegasus to submit to OSG" after we start fully utilizing this node. Will prevent OSG node config errors from slowing us down.

**Comment by mayani** [comment]
Revisit configuring Pegasus to submit to OSG once we start fully utilizing the Mint node.
