### ISSUE TITLE
Does Pegasus instance have a website?

### ISSUE THREAD

**Issue by sirspock** [mintproject/it-mgmt#9]
We have the domain pegasus.mint.isi.edu but we are not using it.
Does Pegasus instance have a website (http)?

**Comment by mayani** [comment]
Pegasus is a command line tool and does not have a web endpoint.

**Comment by rafaelfsilva** [comment]
I second Rajiv on that, so no need for a sub-domain for us.

**Comment by sirspock** [comment]
Ok.
